### ISSUE TITLE
Error: Default server or group not defined

### ISSUE THREAD

**Issue by jnijland** [muehre/container-manager#3]
Hi,

Whatever I do and wherever I use the plugin, I keep on receiving this error:

```Default server or group not defined``` 

I've tested it on a Rancher/K8S system, and also on a Docker swarm, but on both systems I receive this error. I've edited almost nothing on the config, except for the network name to match the actual network name. 

I also added some server groups to the config and removed the default one's:
```yaml
groups:
  lobby:
    strategy: balance
    can-reconnect: true
    restricted: false

default-group: lobby

join-commands:
  lobby: default
  hub: default
```

Could you tell me what I'm doing wrong? Thanks!
